### ISSUE TITLE
VersionBot: Have the ability to force/require certain commit footer tags

### ISSUE THREAD

**Issue by agherzan** [resin-io-modules/resin-procbots#144]
Would be nice to have a configurable option in the local repository config file which will be taken into consideration by versionbot when checking required tags for commits. As well there should be a way of setting if the tag is required globally in the PR (at least once) or in every commit. Useful for example when forcing `changelog-entry`.

This would be a more general solution to https://github.com/resin-io-modules/resin-procbots/issues/142 .

**Comment by hedss** [comment]
We could achieve this with an entry in the `.procbots.yml` files:
```
versionbot:
  required-tags:
    - "signed-off-by"
    - "changelog-entry"
```

**Comment by agherzan** [comment]
@hedss please take into consideration a configuration which would specify if a certain tag is needed in all commits or at least one
