### ISSUE TITLE
VersionBot: 'invalid username or password' intermittent error

### ISSUE THREAD

**Issue by pimterry** [resin-io-modules/resin-procbots#166]
Example: https://github.com/resin-io/resin-api/pull/308#issuecomment-311463051

Worked fine after adding and removing the label a little later (after an unrelated build hiccup), with no other changes. Nothing visible in the github status stats.

**Comment by hedss** [comment]
Seen this occasionally, since we started. I think it's a GHism, which for some reason fails the clone and then happily accepts it after. I'll add a retry into the mechanism for cloning, similar to how the GH Service itself works.
