### ISSUE TITLE
VersionBot: Suppress warning when PRs are a WIP

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#172]
At the moment, any failing status check post-push will cause the author of the PR to receive a warning that the check has failed.

@pcarranzav has asked if there's a way to disable this. Whilst there isn't, it makes sense to have a new label that can be added to a PR to say 'Don't warn me of any status failures' (of course the statuses should still fail/succeed as required).

**Comment by lurch** [comment]
Does the `no-checks` label not already do that? Or is this a suggestion for a more "fine grained" control (i.e. don't report failing status checks, but do report everything else) ?

**Comment by hedss** [comment]
This conversation links to https://www.flowdock.com/app/rulemotion/r-process/threads/kOQTS5_DRZMWkQxwdF-42_YmqMX

For clarity, @lurch, `no-checks` is designed to stop VB doing *anything*. Pablo required the ability to squelch warnings.

**Comment by lurch** [comment]
Yeah, I've been reading that thread ;)

**Comment by hedss** [comment]
This will now work by ensuring that when the `flow/in-progress` label is applied to a PR, no warnings will be reported. This allows us to use existing labels to get the desired results.
