### ISSUE TITLE
SyncBot: Integrate with billing and flag unpaid users' support@ emails

### ISSUE THREAD

**Issue by brownjohnf** [resin-io-modules/resin-procbots#181]
It would be great if SyncBot could notice non-paid users emailing us in support, and send a canned response back to the user asking them to use the forum. Then we'd see it in support and know we can close it.

**Comment by sqweelygig** [comment]
@sonyagreen I think this can be done using the existing functionality within Front, and would prefer to use native tools where available.  Something like the attached.  What do you think?
![front_rule](https://user-images.githubusercontent.com/20857369/28111054-1de44824-66ec-11e7-9411-b7282303aedd.png)

**Comment by sqweelygig** [comment]
I'm going to close this ticket down.  It's not really SyncBot's job, and is available through Front inbox rules.

**Comment by sonyagreen** [comment]
Agreed it's not Syncbot's job.  Currently this isn't possible in Front because it doesn't know if a user is paid or free.
