### ISSUE TITLE
VersionBot: Ready-to-merge causes an endless stream of comments for PRs with conflicts

### ISSUE THREAD

**Issue by pimterry** [resin-io-modules/resin-procbots#224]
If you accidentally add 'ready-to-merge' to a PR that isn't mergeable, versionbot posts "Pull Request is not mergeable" errors over and over again every couple of minutes until you remove the label. Example: https://github.com/resin-io/resin-api/pull/392

Admittedly, you shouldn't do this in the first place, and it certainly did make sure that I noticed that I needed to fix this, but it would be nice if versionbot could tell me off for my foolish mistakes a little more quietly.

**Comment by hedss** [comment]
I'm (fairly) convinced this is now fixed as part of the checks to status kicks that went into the last deploy. If we see this occur again, I'll re-open.

**Comment by lurch** [comment]
Pinging @jviotti to watch out for this too, as I know it's something he's seen.
