### ISSUE TITLE
SyncBot: Front comment is confusing

### ISSUE THREAD

**Issue by sonyagreen** [resin-io-modules/resin-procbots#242]
>Connects to flowdock thread YlwQNXFR4qfMQkOfgAHFrIs_xdQ

sounds like a generically related FD thread. Instead consider:

>This ticket is mirrored in Flowdock thread YlwQNXFR4qfMQkOfgAHFrIs_xdQ

**Comment by sqweelygig** [comment]
Anticipating future uses of SyncBot I'm going to leave the "ticket" out, because it will be syncing a lot more than just tickets, and instead write "This is mirrored in ..."
