### ISSUE TITLE
VersionBot: Could be used to notify PR originators that a build has failed

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#3]
@pimterry made the suggestion in resin-io/resin-ui#28, but essentially when a status check fails,  we could automatically comment on the status pinging the originator of the PR so they know.

**Comment by lurch** [comment]
...and if this is added, a user might want the ability to 'unsubscribe' from these build-failure notifications? (maybe, I'm just guessing)

Also, there might need to be a way to configure this per status-check-service, as an (entirely different) repo on which I'm a contributor uses Codecov which automatically comments on the PR itself.

**Comment by lurch** [comment]
And just to be pedantic, the original suggestion was in https://github.com/resin-io/resin-ui/pull/324  ;-)

**Comment by hedss** [comment]
@lurch There's the ability to turn off VersionBot in a PR (`procbots/versionbot/no-checks` label when the PR is opened). Apart from that, a single comment is now provided on a PR the first time incorrect commits are seen (when the PR is opened). The status check will stay in a failed state but no further comments will be issued.

By commenting as soon as the PR is opened, it should be obvious in a notification list that something needs correcting. I think this is valid, as VersionBot never spams the author.

**Comment by lurch** [comment]
Hmmm, looking at things from the other point of view (sorry!) if the user **is** relying on VersionBot to notify them of failing status-checks, they *might* expect this behaviour:  (and I'm assuming here that each status-check takes a significant amount of time to run, i.e. the user goes off and does something else in the meantime)
 * User submits their PR
   * status-check fails, user gets a notification message
 * User updates their PR
   * status-check fails again, and according to your last message they don't get a second notification
 * As the user didn't get a status-check failed notification, they assume it succeeded (when in fact it didn't)

?

Then again, perhaps I'm confusing/overlapping what the status-check service should do, with what VersionBot should do.

**Comment by hedss** [comment]
Status checks for commits/merges in VersionBot are quick, less than a couple of seconds after the Github hook has fired. Jenkins is the real slowpoke, and you're going to come back for that anyway.

Almost as soon as a PR is opened, VersionBot will let you know if a commit is incorrect, which is why it only comments directly at the author once. This means the next commit should include a correct commit type. If it doesn't, the author's forgetful. The fact that the status itself will still fail and stop you from merging a PR is the ultimate reminder, just as Jenkins failures is a 'this code is broken'.

Because of this, I don't see any advantage to flagging a failing `versionist` commit more than once in the PR.

**Comment by lurch** [comment]
Right. I guess what I was asking is: do failing-tests on Jenkins/Travis automatically notify the author from within Jenkins, or is that something that VersionBot could (also) do?

**Comment by lurch** [comment]
...or perhaps that's a job for a separate StatusBot, rather than VersionBot ;)

**Comment by hedss** [comment]
Most of our CI tests do nothing more than failing the status of the last commit. In fact, VersionBot does *way* more than they do, by informing the author in the first place.

I think this would be more a StatusBot. Again, VersionBot has a very specific role, and I'm highly against having a single bot that does tonnes of stuff. It makes it extremely inflexible and means runtime control becomes a real pain!

**Comment by lurch** [comment]
> I'm highly against having a single bot that does tonnes of stuff.

Agreed - sensible separation of responsibilities always makes sense. Apologies if I've been conflating VersionBot with SomeOtherPotentialProcBot.
Perhaps the issues in this repo could be categorised with `VersionBot` and `OtherProcBot` labels? ;-)

**Comment by lurch** [comment]
Hmmm, with one eye towards there being other ProcBots in future, I wonder if it'd be worth considering a 'global' `procbots/no-checks` label, and then telling VersionBot to ignore any PRs that are flagged with `procbots/versionbot/no-checks` _or_ `procbots/no-checks` labels? Possibly that's jumping the gun a bit at this early stage...

**Comment by hedss** [comment]
Yeah, I have ideas about how the others will work but I really don't want to start wandering off in these directions given I know what my short to medium workload is going to be based on. To that degree, maybe I should label a lot of these issues as 'not for current review'.

**Comment by hedss** [comment]
This is duplicated by #99, which is referenced in #123.

Closing.
