### ISSUE TITLE
VersionBot: Changelog can get easily out of sync with npm

### ISSUE THREAD

**Issue by pimterry** [resin-io-modules/resin-procbots#30]
Versionist right now will add versions to the changelog that aren't available on npm. This requires maintainers to remember to publish a new version every time Versionist merges a PR.

We could provide scripts for at least npm (maybe other platforms?) to automatically publish a release, when a new version is added to the changelog on master. Connects to https://github.com/resin-io/hq/issues/577.

**Comment by emirotin** [comment]
Should the `connects` part link to a different repo?

**Comment by pimterry** [comment]
@emirotin Yes, good spot, fixed.

**Comment by lurch** [comment]
Also kinda-related to https://github.com/resin-io/versionist/issues/69 and/or https://github.com/resin-io/versionist/issues/68 ?

**Comment by lekkas** [comment]
@pimterry If we follow the `release` branch convention for grouping PRs discussed in https://github.com/resin-io-modules/resin-procbots/issues/16 , then it looks like we can actually close this ticket, right?

**Comment by pimterry** [comment]
@lekkas I think we still independently want this. That grouping approach ensures we can manage versions explicitly when required, so we're slightly less likely to accidentally do a release and forget to publish it, but it doesn't make it automatic, it just helps a bit. I think there's still value in having versionbot (potentially via versionist) publish to npm automatically, both to avoid forgetting and to make maintainers lives easier.

**Comment by lekkas** [comment]
@pimterry I see. I agree that we should automate publishing as well, but I think this should be a handled by the agent/bot that handles builds, like TravisCI/Jenkins etc (also suggested by @brownjohnf) as opposed to being handled by VersionBot. There's an open arch call item to discuss this today FYI.

**Comment by lurch** [comment]
> I agree that we should automate publishing as well, but I think this should be a handled by the agent/bot that handles builds, like TravisCI/Jenkins etc

@jviotti Recently updated [Etcher](https://github.com/resin-io/etcher) to do [exactly that](https://github.com/resin-io/etcher/pull/1078) for snapshot builds - see the results at https://resin-nightly-downloads.s3.amazonaws.com/

**Comment by lekkas** [comment]
Thanks for the heads up @lurch 👍

**Comment by hedss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VersionBot: Changelog can get easily out of sync with npm](https://trello.com/c/Ll9Xlhug/7-versionbot-changelog-can-get-easily-out-of-sync-with-npm)

**Comment by alexandrosm** [comment]
@hedss does this close now with the publishing moved to the build step?

**Comment by hedss** [comment]
Yep, closing.
