### ISSUE TITLE
Add unit test framework

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io-modules/resin-procbots#321]
We should add a mocha/chai unit test framework.
The structure of this should follow the pattern used in the `resin-ui` repo.
Tests should be in a `test` directory in the root of the project.
Test files should match the name of the file they are testing, and end with `.spec.ts`.
You can use `ts-node` to test `.ts` files with mocha.
The test command would most likely be `mocha --require ts-node/register ./test/*.spec.ts`.

Dependencies would be:
- `mocha`
- `chai`
- `ts-node`
- `@types/mocha`
- `@types/chai`

The tests should be run as part of the CI process.

**Comment by sqweelygig** [comment]
@LucianBuzzo is this issue closed?

**Comment by LucianBuzzo** [comment]
@sqweelygig yes it is!
