### ISSUE TITLE
VersionBot should wait a few seconds to ensure GH API matches sent status event

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#36]
Sometimes, the GH API appears to not get the recently updated status changes. We need to delay a few seconds to give it a little more time to catch up.

**Comment by lurch** [comment]
Do we also need to leave a bit of a time-gap after detecting a new PR, to allow the person submitting the PR to apply the `procbots/versionbot/no-checks` label as necessary?

**Comment by hedss** [comment]
You can apply a label before the PR is even opened, so I would expect people to do this.

**Comment by lurch** [comment]
Hah, I didn't know that ;-)
Worth mentioning in (the spec pointed to by) https://github.com/resin-io/hq/pull/633 ?

**Comment by hedss** [comment]
Already in it: :)
"6. If, for some reason, VersionBot should not be used to automatically check commits for the Change-Type: semver tag, or to stop automatic PR merging, apply the procbots/versionbot/no-checks label to the PR."

**Comment by lurch** [comment]
Nah, it was specifically the "applying a label before the PR is even opened" bit I was referring to.
But given my lack of previous-label-usage, perhaps I'm unusual in not knowing that that's actually possible? (in this case, I guess it's effectively mandatory to apply the `procbots/versionbot/no-checks` label before opening the PR, if you want it to behave as expected)

**Comment by hedss** [comment]
This is essentially dead. We now work on all `status` events sent, which ensures that when GH catches up, we get triggered again because of the event.
