### ISSUE TITLE
VersionBot should ignore the unlabeling of a PR

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#37]
Currently it doesn't, so it checks to try and do a merge for both labeling (ie. `procbots/versionbot/ready-to-merge`) and *any* unlabeling. It should ignore the latter, as nothing VersionBot does is affected by it, and if it does see the merge label is set, it will attempt to carry out a merge again (this won't corrupt anything, but will flag an error).

We see this as some users have scripts running labeling/unlabeling PRs as their status changes.

**Comment by lurch** [comment]
What about the situation where the `procbots/versionbot/no-checks` label gets removed - the user might then expect VersionBot to do the checks it'd been previously told to skip?

**Comment by lurch** [comment]
> We see this as some users have scripts running labeling/unlabeling PRs as their status changes.

Maybe this is another situation where we need to insert a time-gap? i.e. if a label gets removed, wait for e.g. a couple of minutes to see if it gets added back again (in which case no action should be taken), before responding to the unlabelling event (if the label didn't get re-added)? IYSWIM.

Apologies if you've already considered that and I'm just adding 'noise'.

**Comment by hedss** [comment]
Should the label get removed then a check will occur the next time a status update occurs or a synchronization is forced (and in fact if the `procbots/versionbot/ready-to-merge` label is applied).

Re-labelling events are automatic, they will be seen so we do not need to wait for them.

Closing this issue as it's working as it should.

**Comment by lurch** [comment]
Perhaps it'd be worth adding something to the docs to explain how to 'manually force' VersionBot to run checks after removing the `procbots/versionbot/no-checks` label?
(or perhaps I'm still just misunderstanding things!)

**Comment by hedss** [comment]
There is a section in the PR and commit guidelines spec. that mentions how to kick VersionBot to restart.
