### ISSUE TITLE
SyncBot: Files don't reach Flowdock

### ISSUE THREAD

**Issue by sqweelygig** [resin-io-modules/resin-procbots#380]
cc @sqweelygig - not sure if this is on your queue: file uploads to Front (via Intercom?) just become <div></div> when they reach Flowdock

**Comment by lekkas** [comment]
One more comment about Discourse/Front image rendering from https://www.flowdock.com/app/rulemotion/d-bots/threads/0VVFMSSEhuI6cnw0AeZ5R6GNxKf

> [...] see if we can somehow render pictures that users have uploaded

> discourse make it very easy to upload screenshots and users seems to like it, I've seen quite a few conversations where we exchange screenshots so it might worth looking into it

**Comment by sqweelygig** [comment]
https://www.flowdock.com/app/rulemotion/public-s-premium/threads/syF-1j1vbbCeWw1ehvTsMDwNZ-E

**Comment by sqweelygig** [comment]
Duplicate of the image rendering stuff, it's just making sure that hyperlinks get passed around the place.
