### ISSUE TITLE
VersionBot should only check for a `Change-Type` tag on the footer of a commit.

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#39]
Without doing this, `versionist` will fail.

**Comment by lurch** [comment]
Is this something that should be checked by `versionist` itself, rather than VersionBot? \*shrug\*

**Comment by hedss** [comment]
@lurch I and @lekkas have discussed this, and ideally it absolutely should. I can't find the relevant issue right now, but yes. What should be happening is `VersionBot` pulls in `versionist` as an NPM module and uses it programatically, getting any errors/failures back and then using them to percolate up the chain.

Unfortunately, up to now `versionist` has been a bit of a moving target, so executing it as command seemed the easiest way to ensure compatibility.
