### ISSUE TITLE
Versionbot doesn't ignore already merged PRs

### ISSUE THREAD

**Issue by pimterry** [resin-io-modules/resin-procbots#50]
See https://github.com/resin-io/resin-ui/pull/450#discussion_r102524450, where a comment on the PR after merge triggered an error.

**Comment by hedss** [comment]
This is down to the `procbots/versionbot/ready-to-merge` label still being assigned, and because a `pull_request` event is being fired on comments. Essentially, the label should be automatically removed on a successful merge.

**Comment by hedss** [comment]
It does now, the unlabeling occurs and further comments do not provoke it.

**Comment by lurch** [comment]
Do not provoke the VersionBot, lest you feel its wrath.

**Comment by hedss** [comment]
More of a nasty suck, tbh. :)

**Comment by lurch** [comment]
Do not provoke the VersionBot, lest it spams multiple identical comments on your PRs :laughing:
