### ISSUE TITLE
SyncBot: Front sometimes drops the Discourse topic titles

### ISSUE THREAD

**Issue by lekkas** [resin-io-modules/resin-procbots#538]
From https://www.flowdock.com/app/rulemotion/d-bots/threads/0VVFMSSEhuI6cnw0AeZ5R6GNxKf

> The title is the user's username for some reason, instead of the actual thread topic title. I thought that this might be a case where the title was changed, but it doesn't look like that's the case (but don't take my word for it, maybe I missed something in the edit history)

**Comment by lekkas** [comment]
Example thread: https://app.frontapp.com/open/cnv_soyu97

**Comment by sqweelygig** [comment]
Not seen this in ages, so I'm going to close it.
