### ISSUE TITLE
SyncBot: MD code formatting is off in some cases

### ISSUE THREAD

**Issue by lekkas** [resin-io-modules/resin-procbots#539]
From https://www.flowdock.com/app/rulemotion/d-bots/threads/0VVFMSSEhuI6cnw0AeZ5R6GNxKf

> MD rendering for code snippets looks a bit off, that's easy to spot if you compare the first message from the user in Discourse and Front

example thread: https://app.frontapp.com/open/cnv_soyu97

**Comment by sqweelygig** [comment]
I've just done a quick attempt to reproduce, couldn't.  Also done a sweep of recent forums threads for re-incidents, and didn't find any.  I'm going to keep an eye out for this happening again.

**Comment by lekkas** [comment]
@sqweelygig that interesting, doesn't using the same content with the first message at https://forums.resin.io/t/module-version-mismatch-when-running-sudo-resin-local-configure/3197 reproduce it?

Note that the message has been edited, maybe syncbot fetched the first version

**Comment by sqweelygig** [comment]
SyncBot will have totally used the first version, but I couldn't see any sign of an edit.  Perhaps it's permissions or my ability with the Discourse UI.  @lekkas could you point me at where I'd find edits?

**Comment by sqweelygig** [comment]
nvm, I've done that thing where you continue digging just in case you can find it while hoping for a response, and found it!

**Comment by sqweelygig** [comment]
I note that SyncBot accurately reproduced the first version of this post, and this is therefore a manifestation of SyncBot's inability to edit messages (tracked here https://github.com/resin-io-modules/resin-procbots/issues/494)

**Comment by lekkas** [comment]
Awesome, thanks @sqweelygig
