### ISSUE TITLE
VersionBot has been seen failing a `git clone` operation

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#58]
See resin-io/resin-ui#499 
Looks to be a Github API hiccup, as a local test worked, as did re-applying the merge label. :-/

**Comment by lurch** [comment]
I'm fairly sure I've also seen `git clone` fail on TravisCI before too (I think it might have been some kind of timeout). Can't remember now which project that was on though.
The 'fix' was to manually restart the build, and on the second attempt everything worked fine.

**Comment by hedss** [comment]
@lurch Thanks! Yeah, I actually had a play over the weekend, trying multiple ways to get this to fail and couldn't. I did see some timeouts last week, so it probably explains this. As I say, re-applying the label worked, so I suppose I should just close this and try and get in if it happens again. :-/
