### ISSUE TITLE
Allow defaulting Changelog-Entry to commit's subject line

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/resin-procbots#61]
Considering a commit will likely often have the same Changelog-Entry as it's subject line, defaulting to it if no Changelog-Entry field is present in the footer might save a bit of duplication and typing.

**Comment by lurch** [comment]
I think it might do this already?

**Comment by hedss** [comment]
Yeah, if you don't supply a `Changelog-Entry` tag then it defaults to the header (first line of the commit).

**Comment by hedss** [comment]
If I don't hear back within 24 hours, I'm closing this. ;-)

**Comment by jhermsmeier** [comment]
Okay, I thought you said that it'll complain if that's missing - must have misunderstood :)

**Comment by lurch** [comment]
It complains if there are no commits with a `Change-Type:` footer. Easy to mis-hear things on video-conference :)

**Comment by hedss** [comment]
Flarble gurgle floggle lump.

Got that? Right! :)

**Comment by jhermsmeier** [comment]
Oh yes, that was it! Not sure how I managed to get that mixed up 😄
