### ISSUE TITLE
VersionBot: Multi-status Integrations can cause status check to fail

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#62]
See: https://github.com/resin-io/node-lkl/pull/17

It appears that the branch protection has a single Travis entry, but the number of Travis status checks can differ. This breaks the check algorithm, causing VersionBot to fail.

**Comment by lurch** [comment]
From a quick rummage, looks like https://github.com/resin-io-modules/resin-procbots/blob/master/lib/bots/versionbot.ts#L819 is the troublesome line? (but of course I could easily be wrong)

**Comment by hedss** [comment]
Yes it is, but I need to check to ensure multi-status would be fixed by always being '>=', which given the Travis layout, I'm not sure.

**Comment by lurch** [comment]
Yeah, I guess if you had integrations from Travis, AppVeyor and Jenkins, then VersionBot would (naively?) be looking for at least 3 status checks. But if Travis and AppVeyor returned two status checks each, then VersionBot might think it's "good to merge" even if the Jenkins status-check hasn't completed yet?
Obviously you could change the logic to check that each integration has returned at least one status-check, but that might still go wrong if the first Travis check passes, and VersionBot thinks things are good-to-merge before the second Travis check fails.

Perhaps this is something else that needs to be configurable via `.procbots.yml` ?  (if you can't get the info you need from the Github API)

**Comment by hedss** [comment]
You keep reading my mind. :)

The main problem here is, again, Github's API has changed since they first designed it, which has lead to backwards compat. lockin. I'm going to see if there's another way I can get min. potential checks somehow.

**Comment by lurch** [comment]
...and as I think I might have mentioned elsewhere, there's also some services (e.g. CodeCov) where you want the status-checks displayed for informational purposes, but you might not want a failing CodeCov status check to actually block the VersionBot merging process. (but obviously that's a bridge that's probably not worth crossing until we actually get to it)

**Comment by hedss** [comment]
In fact for things such as the latter, it's not an issue. If a status is not included in the protected branch settings, then it's not flagged by Github and VB won't look for it.

The other thing I should have mentioned was that statuses are all cleared when a new commit occurs, so we won't get into a situation where VB okays something if a check hasn't been carried out. You can actually see this in how it currently works, where after it commits a new version bump, it has to wait until Jenkins has finished building.

**Comment by lurch** [comment]
> In fact for things such as the latter, it's not an issue. If a status is not included in the protected branch settings, then it's not flagged by Github and VB won't look for it.

Ahhh, cool. I've never added status-checks to a repo nor set up protected branches ;-)

**Comment by pimterry** [comment]
Looks like there's a fix for this, but I think I'm seeing a bug over here: https://github.com/resin-io/resin-ui/pull/556#issuecomment-286348771

PR was all passing and reviewed and happy, I added ready-to-merge label, and versionist committed its version update, then instantly added a comment complaining it couldn't see a jenkins build yet for that commit, because it didn't start for a minute or so. It did then finish up and merge once the jenkins build completed though, just an annoying extra comment.

**Comment by pimterry** [comment]
Is there any progress on this? It's been pinging a least one extra error comment on every single UI PR for a month and a half now, and it's quite annoying. Some examples from today alone:

* https://github.com/resin-io/resin-ui/pull/686
* https://github.com/resin-io/resin-ui/pull/690
* https://github.com/resin-io/resin-ui/pull/688
* https://github.com/resin-io/resin-ui/pull/687

Some of these errors pings get duplicated as well for some reason as well, not sure what's up with that.

**Comment by hedss** [comment]
@pimterry I've been prioritised on other things up to now. I still have some stuff to finish off next week, but it's fully my intention to start working through this and the other high priorities next week.

Sorry it's frustrating. :(

**Comment by pimterry** [comment]
Ok, great, that's fine! Thanks, just checking it hasn't got lost somewhere :-).
