### ISSUE TITLE
VersionBot: Merge as soon as PR has been correctly approved (remove `procbots/versionbot/ready-to-merge` label)

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#72]
Currently a maintainer has to return to PRs to allow them to be merged by VB.

VB could look for approvals in PRs and then automatically merge when the requisite number or approved reviewers have approved it (config file required for number/list of approved reviewers).

Maintainers would no longer need to 'throw the switch'.

**Comment by hedss** [comment]
See #27, see #64.

**Comment by LucianBuzzo** [comment]
I'd really like this to be optional.
On the UI the ability to decide to manually merge is very important.
We should only be merging if we plan to deploy to staging and go through a testing process.

**Comment by lurch** [comment]
@LucianBuzzo Perhaps things should be switched around, and instead of waiting-to-merge and deploy-immediately-to-staging, it'd be better to immediately-merge and wait-to-deploy-to-staging? \*shrug\*

**Comment by LucianBuzzo** [comment]
@lurch Sorry for being dense, I don't understand what you mean. Could you please explain further?

**Comment by lekkas** [comment]
@hedss I don't think we should drop the label completely, see https://github.com/resin-io-modules/resin-procbots/issues/27#issuecomment-288358564

**Comment by LucianBuzzo** [comment]
The window between merging a change into master and having that change production 
ready needs to be as small as possible.

Auto-merging runs against this as the engineer who issued the PR maybe 
unavailable to ensure their change is production ready at the point that the 
merge happens.
Ensuring that a change is production ready involves smoke testing it on staging, 
and if the engineer doesn't do this immediately after the merge then we are 
opening up the window in which we have unready changes on the master branch.
If the PR is auto-merged this is reducing the ability for maintainers to keep 
their deployment pipelines clear and to schedule releases.  

We need to keep our deployment pipeline as clear as possible and I think our 
process for deployments and updates should be focused on this. 

If the pipeline is clear it makes hotfixing production trivial, without needing 
complicated branching/cherry-picking, as we can simply create a new tagged 
release and push it through to production. 
It doesn't matter if your change isn't deployed to production, it just needs to 
be *production ready*, so if a hotfix with high priority comes through after it, 
it doesn't matter if the previous versions are deployed at the same time.

I think the dev --> production process looks like this:
1) Local testing, manually and with automated testing tools
2) Code review from Peers on PR
3) Merge to master
4) Immediately deploy new version to staging and smoke test
5) If smoke test is unsuccessful start from step 1 and submit a PR fix.
6) Change is now *production ready* and is safe to leave.

We want to keep the time between step 3 and step 6 as small as possible.

cc @lekkas @alexandrosm

**Comment by hedss** [comment]
I think @LucianBuzzo has some extremely good points here, and this does ring true with the conversation we had a couple of weeks back. I understand the point is to use DeployBot to deploy to the correct environment when ready, but it certainly doesn't allow the sidestepping of the hotfix issue and would also force testing in series and at the end of the day, we're trying to make life easier for engineers, not harder. We should probably discuss this again in a process brainstorm, shall create a tag linking to this issue.

**Comment by hedss** [comment]
Closing this issue as #73 now tends to the root problem.
