### ISSUE TITLE
Procbots command labels should follow consistent format

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#9]
We wish to use labeling going forward to control Procbot implementations. This should follow the:

`procbots/<bot>/<command>`

format.

[hq edit] connects to https://github.com/resin-io/hq/pull/443

**Comment by lekkas** [comment]
Just adding a note here on updating the README as well to reflect the changes to the commands

**Comment by lekkas** [comment]
Also, given that merging is handled by `versionbot`, shouldn't 

`triggerLabels: [ 'flow/ready-to-merge' ]` 

be changed to `triggerLabels: [ 'procbots/versionbot/ready-to-merge' ]` as well?

(https://github.com/resin-io-modules/resin-procbots/blob/master/lib/versionbot.ts#L95
