### ISSUE TITLE
SyncBot: enable >2 services

### ISSUE THREAD

**Issue by sqweelygig** [resin-io-modules/resin-procbots#90]
At the moment some of the assumptions within SyncBot are that only 2 services are synced.  This is not the case, and needs a little coding to account for.

**Comment by sqweelygig** [comment]
To enumerate this rather sparse description, the concept of 'genesis' to protect against infinite loops could be improved to describe a journey across many locations.

**Comment by sqweelygig** [comment]
This might not be required, depending on the results of "how do we structure rooms"

**Comment by hedss** [comment]
@sqweelygig Is this now closeable?
