### ISSUE TITLE
SyncBot: Verify Flowdock listener

### ISSUE THREAD

**Issue by sqweelygig** [resin-io-modules/resin-procbots#91]
The Flowdock listener is currently unverified around the concept of thread creation, and I'm suspicious that it might not.  I need to ensure that this fires correctly.

**Comment by sqweelygig** [comment]
I have just confirmed that there is a small bunch of work revolving around message-converters in supporting a greater diversity of thread events.  This work should include:
* Atomic thread creation events
* Flowdock threads might be event source
* Flowdock threads might be private
* Discourse threads might be event destination

**Comment by hedss** [comment]
@sqweelygig Is this now closeable given the deployment to K8?
