### ISSUE TITLE
VersionBot: Warn author should any of the status checks fail

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#99]
@flesler has suggested that an author of a PR should be pinged should a status check on a PR fail (author of the PR rather than author of the commit, as the PR is the responsibility of the author).

Fairly simple algorithm. Check status failures as per normal, check to see if VB posted a comment after that date, if not then post comment informing a failure has occurred. If comment already exists, ignore (to prevent spam).

**Comment by lurch** [comment]
Does this partially conflict with #88 ?

**Comment by hedss** [comment]
No, #88 was about reducing spam where pending items were flagged as failures. If you've used VB in the last week you'll note that it's *extremely* quiet now, unless something does actually go wrong.

This issue is about ensuring that, should a status failure actually occur, then the original author of the PR is explicitly pinged so they know to come back to it (there are quite a few engineers who don't look at a PR again until it's been reviewed, and reviewers who won't look at a PR if it fails, so this reduces deadlock).

As mentioned above, the comments will be date checked. Should a status failure have occurred and the author have been pinged *since* that failure, then it will be ignored.

**Comment by lurch** [comment]
> so this reduces deadlock

:tada:
